steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hand-pose-backend:$COMMIT_SHA', './backend']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hand-pose-backend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  # Note: Environment variables are preserved automatically by Cloud Run 
  # across deployments. Do not add --clear-env-vars here.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hand-pose-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hand-pose-backend:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/hand-pose-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
